# Generated by Django 2.2.17 on 2020-11-18 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_customtext_wsdfwsaz"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customtext",
            name="wsdfwsaz",
        ),
    ]
