# Generated by Django 2.2.17 on 2020-11-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_customtext_wsdfwsaz"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hgkhgj",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hgfjhfgjhgfjhgfjhgfruyr", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Hlkgfdgfgfgdgfdgfdtrrerertersdadsdadsadsads",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("j598090980980980989080980845654", models.BigIntegerField()),
            ],
        ),
    ]
